#!/usr/bin/perl -sw
##
##
##
## Copyright (c) 1999, Vipul Ved Prakash.  All rights reserved.
## This code is free software; you can redistribute it and/or modify
## it under the same terms as Perl itself.
##
## $Id: changecolor,v 1.1 2001/10/22 06:01:25 hackworth Exp $

use GD; 

open GIF, "test.gif" || die; 
my $gif = GD::Image->newFromGif(GIF) || die;
close GIF; 

my $white = $gif->colorAllocate( 255, 255, 255 );
$gif->colorDeallocate( $white );
$gif->colorAllocate( 0, 0, 0 ); 

open  GIF, ">test.gif"; 
print GIF  $gif->gif;
close GIF; 


