#!/usr/bin/perl -swI..
##
## codd-realnames -- Collate different entries for the same developer. 
##
## $Date: 2001/10/22 06:01:25 $
## $Revision: 1.1 $
## $State: Exp $
## $Author: hackworth $
##
## Copyright (c) 1998, Vipul Ved Prakash.  All rights reserved.
## This code is free software; you can redistribute it and/or modify
## it under the same terms as Perl itself.

 
use Code::Contribution::Distribution; 

%REALNAMES = (

	'free software foundation, inc'  => 
     	[ 'free software foundation\s*$', 
           '^the free software.*', 
        ], 

	'the regents of the university of california' => 
		[ '.*regents of the university of california.*', ],

	'digital equipment corporation' => 
		[ '.*digital equipment corporation.*' ], 
	
	'silicon graphics, inc' => [ '.*silicon graphics.*' ], 
    'at&t bell laboratories'  => [ 'at\&t.*' ], 

	'larry wall'       => [ 'login-lwall', 'larry\@wall.*', 'lwall\@.*', ], 
	'paul vixie'       => [ 'login-vixie' ], 
	'tom christiansen' => [ 'tchrist\@.*' ], 
	'richard stallman' => [ 'richard m\. stallman' ], 
	'rich salz'        => [ 'rsalz\@.*' ],
	'jamie zawinski'   => [ '.*jamie zawinski.*', 'jwz\@.*', 'login-jwz' ], 
	'david bagley'     => [ 'bagleyd\@source.*', 'bagleyd\@bigfoot.*', 
                            'david albert bagley.*', ],
	'alan cox'         => [ 'a\.cox.*', 'alan\.cox.*', ], 

); 

my $codd = new Code::Contribution::Distribution Codd => shift; 
my ( $key, $realname, $subst ) = ( undef, undef, 0 );

for $key ( keys %$codd ) { 
	unless ( $key =~ /^__/ ) { 
		for $realname ( keys %REALNAMES ) { 
			for ( @{ $REALNAMES{ $realname } } ) { 
				if ( ( $key =~ /$_/ ) && ( $key ne $realname ) ) { 
					$codd->{ $realname } = $codd->{ $realname } + $codd->{ $key }; 
					delete $codd->{ $key };
					$subst++; 
				}
			}
		}
	}
}

$codd->commit (); 
print "$subst Substitutions. \n\n"; 

