#!/usr/bin/perl -sw
##
##
##
## Copyright (c) 1999, Vipul Ved Prakash.  All rights reserved.
## This code is free software; you can redistribute it and/or modify
## it under the same terms as Perl itself.
##
## $Id: makegif,v 1.1 2001/10/22 06:01:25 hackworth Exp $

use GD;

my $im = new GD::Image(300,300);
my $color; 

$im->transparent($white);
$im->interlaced('true');

for ( 0 .. 255 ) { 
    $color = $im->colorAllocate( $_, $_, $_ );
    $im->arc ( 150, 150, 255-$_, 255-$_, 0, 360, $color );
}

open GIF, ">test.gif"; print GIF $im->gif; close GIF;


